//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionMVC.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioWS.IService_Usuarios")]
    public interface IService_Usuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Usuarios/Ingresar_usuario", ReplyAction="http://tempuri.org/IService_Usuarios/Ingresar_usuarioResponse")]
        string Ingresar_usuario(string nombre, string apellido, string usuario, string clave, string telefono, string correo, int edad, int sexo, int codDist, int codDpto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Usuarios/Login_usuario", ReplyAction="http://tempuri.org/IService_Usuarios/Login_usuarioResponse")]
        string Login_usuario(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Usuarios/Get_Position_Usuario", ReplyAction="http://tempuri.org/IService_Usuarios/Get_Position_UsuarioResponse")]
        string Get_Position_Usuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Usuarios/Editar_usuario", ReplyAction="http://tempuri.org/IService_Usuarios/Editar_usuarioResponse")]
        string Editar_usuario(int codigo, string nombres, string apellidos, string email, string usuario, string clave, string telefono, bool sexo, int codDist, int codProv, int codDpto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Usuarios/Listar_Distrito", ReplyAction="http://tempuri.org/IService_Usuarios/Listar_DistritoResponse")]
        string Listar_Distrito(int idDpto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_UsuariosChannel : AplicacionMVC.UsuarioWS.IService_Usuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_UsuariosClient : System.ServiceModel.ClientBase<AplicacionMVC.UsuarioWS.IService_Usuarios>, AplicacionMVC.UsuarioWS.IService_Usuarios {
        
        public Service_UsuariosClient() {
        }
        
        public Service_UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ingresar_usuario(string nombre, string apellido, string usuario, string clave, string telefono, string correo, int edad, int sexo, int codDist, int codDpto) {
            return base.Channel.Ingresar_usuario(nombre, apellido, usuario, clave, telefono, correo, edad, sexo, codDist, codDpto);
        }
        
        public string Login_usuario(string usuario, string clave) {
            return base.Channel.Login_usuario(usuario, clave);
        }
        
        public string Get_Position_Usuario(string usuario) {
            return base.Channel.Get_Position_Usuario(usuario);
        }
        
        public string Editar_usuario(int codigo, string nombres, string apellidos, string email, string usuario, string clave, string telefono, bool sexo, int codDist, int codProv, int codDpto) {
            return base.Channel.Editar_usuario(codigo, nombres, apellidos, email, usuario, clave, telefono, sexo, codDist, codProv, codDpto);
        }
        
        public string Listar_Distrito(int idDpto) {
            return base.Channel.Listar_Distrito(idDpto);
        }
    }
}
